
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List
import qrcode
import io
import base64

from app.core.security import get_current_active_user
from app.crud.mfa import (
    create_mfa_device, get_mfa_devices_by_user, get_mfa_device_by_id,
    update_mfa_device, delete_mfa_device
)
from app.schemas.mfa import MFADeviceCreate, MFADevice, MFADeviceUpdate
from app.db.session import get_db
from app.models.user import User

router = APIRouter(prefix="/mfa", tags=["mfa"])

@router.post("/enroll", response_model=MFADevice)
def enroll_mfa_device(
    device: MFADeviceCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
):
    """
    Register a new app-based MFA device for the current user.
    This endpoint generates a QR code for the user to scan with their authenticator app.
    """
    # In a real-world scenario, you'd integrate with an MFA provider SDK/API here
    # to generate the secret and provisioning URI.
    # For demonstration, we'll simulate it.
    secret_key = "YOUR_GENERATED_SECRET_KEY" # Replace with actual secret generation
    provisioning_uri = f"otpauth://totp/YourApp:{current_user.email}?secret={secret_key}&issuer=YourApp"

    # Generate QR code
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(provisioning_uri)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    qr_code_base64 = base64.b64encode(buf.getvalue()).decode("utf-8")

    mfa_device_data = device.dict()
    mfa_device_data["user_id"] = current_user.id
    mfa_device_data["secret_key"] = secret_key
    mfa_device_data["provisioning_uri"] = provisioning_uri
    mfa_device_data["is_verified"] = False # Device needs to be verified after enrollment

    new_device = create_mfa_device(db=db, mfa_device=mfa_device_data)

    # You might want to return the QR code separately or have a dedicated endpoint for it
    # For simplicity, we'll add it to the response model as a transient field.
    # In a production system, this should not be stored in the DB as part of the MFADevice object.
    new_device_dict = new_device.__dict__
    new_device_dict["qr_code_image"] = qr_code_base64

    return MFADevice(**new_device_dict)

@router.post("/verify/{device_id}")
def verify_mfa_device(
    device_id: int,
    code: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
):
    """
    Verify an enrolled MFA device using a code generated by the authenticator app.
    """\n    device = get_mfa_device_by_id(db=db, mfa_device_id=device_id)
    if not device or device.user_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="MFA device not found")

    # In a real application, you would use a library like `pyotp` to verify the code
    # For demonstration purposes:
    is_code_valid = (code == "123456") # Replace with actual OTP verification logic

    if not is_code_valid:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid MFA code")

    # Update device to verified status
    updated_device = update_mfa_device(
        db=db,
        mfa_device_id=device_id,
        mfa_device_in=MFADeviceUpdate(is_verified=True)
    )

    return {"message": "MFA device verified successfully", "device": updated_device}

@router.get("/devices", response_model=List[MFADevice])
def get_mfa_devices(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
):
    """
    Retrieve all MFA devices registered by the current user.
    """
    return get_mfa_devices_by_user(db=db, user_id=current_user.id)

@router.put("/devices/{device_id}", response_model=MFADevice)
def update_mfa_device_settings(
    device_id: int,
    device_update: MFADeviceUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
):
    """
    Update settings for an MFA device (e.g., set as preferred).
    """
    device = get_mfa_device_by_id(db=db, mfa_device_id=device_id)
    if not device or device.user_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="MFA device not found")

    if device_update.is_preferred:
        # If setting this device as preferred, deactivate preferred status for others
        existing_devices = get_mfa_devices_by_user(db=db, user_id=current_user.id)
        for dev in existing_devices:
            if dev.id != device_id and dev.is_preferred:
                update_mfa_device(db=db, mfa_device_id=dev.id, mfa_device_in=MFADeviceUpdate(is_preferred=False))

    return update_mfa_device(db=db, mfa_device_id=device_id, mfa_device_in=device_update)

@router.delete("/devices/{device_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_mfa_device_entry(
    device_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_user)
):
    """
    Delete an MFA device registered by the current user.
    """
    device = get_mfa_device_by_id(db=db, mfa_device_id=device_id)
    if not device or device.user_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="MFA device not found")

    delete_mfa_device(db=db, mfa_device_id=device_id)
    return
